#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
  # Note that the use of brackets around a tr range is ok here, (it's
  # even required, for portability to Solaris 10's /usr/bin/tr), since
  # the square bracket bytes happen to fall in the designated range.
  test "$(git diff --cached --name-only --diff-filter=A -z $against \
          | LC_ALL=C tr -d '[ -~]\0' | wc -c)" != 0
then
  cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
  exit 1
fi

# install this pre-commit via symlink
hook_dst="$(pwd)"/.git/hooks/pre-commit
hook_src="$(pwd)"/pre-commit

if [ -f "$hook_dst" ] && ! diff "$hook_dst" "$hook_src" > /dev/null; then
# if hook already exists and doesn't match, remove
  echo "Existing pre-commit hook doesn't match this one"
  mv "$hook_dst" "$hook_dst".old
fi

if [ ! -f "$hook_dst" ]; then
# if hook doesn't exist (was removed, or never existed), link it
  if ! ln -s "$hook_src" "$hook_dst"; then
    echo "Unable to symlink pre-commit hook"
    exit 1
  fi
  echo "Installed pre-commit hook!"
fi


# run shellcheck for script linting and error catching
files="$(git diff HEAD --cached --name-only | grep ".sh")"
if [ ! -z "$files" ]; then
  echo "$files" | xargs shellcheck -x
  result=$?
  if [ $result -ne 0 ]; then
    echo
    echo "Please address the above issues before committing"
    exit 1
  fi
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
